name: Make release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: Creates a pre-release
      dry-run:
        description: Creates a draft release
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assemblePreview

      - name: Sign apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/preview
          signingKeyBase64: ${{ secrets.SIGNING_KEYSTORE }}
          alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Prepare release
        run: |
          set -e
          
          echo "COMMIT_COUNT=$(git rev-list --count HEAD)" >> $GITHUB_ENV
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Copy build artifacts
        run: |
          set -e
          
          declare -a apks=("universal" "arm64-v8a" "armeabi-v7a" "x86" "x86_64")
          
          printf "%s\n" "${apks[@]}" | xargs -n 1 -I {} sh -c '
          cp app/build/outputs/apk/preview/app-{}-preview-signed.apk mpvKt-{}-r${{ env.COMMIT_COUNT }}.apk
          sha=$(sha256sum mpvKt-{}-r${{ env.COMMIT_COUNT }}.apk | awk '\''{ print $1 }'\'')
          echo "apk-{}-sha256=$sha" >> $GITHUB_ENV'

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: r${{ env.COMMIT_COUNT }}
          name: mpvKt Preview r${{ env.COMMIT_COUNT }}
          body: |
            ### Checksums

            | Variant | SHA-256 |
            | ------- | ------- |
            | Universal | ${{ env.apk-universal-sha256 }}
            | arm64-v8a | ${{ env.apk-arm64-v8a-sha256 }}
            | armeabi-v7a | ${{ env.apk-armeabi-v7a-sha256 }}
            | x86 | ${{ env.apk-x86-sha256 }}
            | x86_64 | ${{ env.apk-x86_64-sha256 }} |
          files: |
            mpvKt-r${{ env.COMMIT_COUNT }}.apk
            mpvKt-arm64-v8a-r${{ env.COMMIT_COUNT }}.apk
            mpvKt-armeabi-v7a-r${{ env.COMMIT_COUNT }}.apk
            mpvKt-x86-r${{ env.COMMIT_COUNT }}.apk
            mpvKt-x86_64-r${{ env.COMMIT_COUNT }}.apk
          draft: ${{ github.event.inputs.dry-run != '' }}
          prerelease: ${{ github.event.inputs.prerelease != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}